<Project Sdk="Microsoft.NET.Sdk">
	<PropertyGroup>
		<LangVersion>Latest</LangVersion>
		<TargetFrameworks>net48;net9.0</TargetFrameworks>
		<ImplicitUsings>enable</ImplicitUsings>
		<Nullable>enable</Nullable>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="EntityFramework" Version="6.5.1" />
		<PackageReference Include="Microsoft.NET.Test.Sdk" Version="17.13.0" />
		<PackageReference Include="MSTest.Analyzers" Version="3.8.3">
			<PrivateAssets>all</PrivateAssets>	
			<IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
		</PackageReference>
		<PackageReference Include="MSTest.TestFramework" Version="3.8.2" />
	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\Library_BasicInfo\Library_BasicInfo.csproj" />
	</ItemGroup>
</Project>
